<a href="https://colab.research.google.com/github/Medynal/Pollution/blob/main/pollution_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import os

repo_url = "https://github.com/Medynal/Pollution.git"
folder_path = "/content/Pollution"

if not os.path.exists(folder_path):
  !git clone {repo_url} {folder_path}
print(f"Current working directory: {os.getcwd()}")


Current working directory: /content


In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score, classification_report, confusion_matrix, mean_squared_error
import joblib
from lightgbm import LGBMRegressor

In [52]:
cpollution_df = pd.read_csv('/content/Pollution/IPNBS/cleaned_pollution_dataset.csv', parse_dates=['Date']).drop(['Month name', 'Date'], axis= 1)
cpollution_df.head()

City  PM2.5    PM10     NO    NO2    NOx    NH3     CO    SO2      O3  \
0  Ahmedabad  73.24  141.54   0.92  18.22  17.15  26.64   0.92  27.64  133.36   
1  Ahmedabad  73.24  141.54   0.97  15.69  16.46  26.64   0.97  24.55   34.06   
2  Ahmedabad  73.24  141.54  17.40  19.30  29.70  26.64  17.40  29.07   30.70   
3  Ahmedabad  73.24  141.54   1.70  18.48  17.97  26.64   1.70  18.59   36.08   
4  Ahmedabad  73.24  141.54  22.10  21.42  37.76  26.64  22.10  39.33   39.31   

   Benzene  Toluene  Xylene    AQI AQI_Bucket  year  month  day  
0     0.00     0.02    0.00  209.0       Poor  2015      1    1  
1     3.68     5.50    3.77  209.0       Poor  2015      1    2  
2     6.80    16.40    2.25  209.0       Poor  2015      1    3  
3     4.43    10.14    1.00  209.0       Poor  2015      1    4  
4     7.01    18.89    2.78  209.0       Poor  2015      1    5

In [53]:
#Cyclical Transformation
# Month
cpollution_df['month_sin'] = np.sin(2 * np.pi * cpollution_df['month']/12)
cpollution_df['month_cos'] = np.cos(2 * np.pi * cpollution_df['month']/12)
# Day
cpollution_df['day_sin'] = np.sin(2 * np.pi * cpollution_df['day']/7)
cpollution_df['day_cos'] = np.cos(2 * np.pi * cpollution_df['day']/7)

#encoding AQI bucket
bucket_encoder = LabelEncoder()
cpollution_df['AQI_Bucket_encoded'] = bucket_encoder.fit_transform(cpollution_df['AQI_Bucket'])

In [54]:
cpollution_df.head()

City  PM2.5    PM10     NO    NO2    NOx    NH3     CO    SO2      O3  \
0  Ahmedabad  73.24  141.54   0.92  18.22  17.15  26.64   0.92  27.64  133.36   
1  Ahmedabad  73.24  141.54   0.97  15.69  16.46  26.64   0.97  24.55   34.06   
2  Ahmedabad  73.24  141.54  17.40  19.30  29.70  26.64  17.40  29.07   30.70   
3  Ahmedabad  73.24  141.54   1.70  18.48  17.97  26.64   1.70  18.59   36.08   
4  Ahmedabad  73.24  141.54  22.10  21.42  37.76  26.64  22.10  39.33   39.31   

   ...    AQI  AQI_Bucket  year  month day  month_sin  month_cos   day_sin  \
0  ...  209.0        Poor  2015      1   1        0.5   0.866025  0.781831   
1  ...  209.0        Poor  2015      1   2        0.5   0.866025  0.974928   
2  ...  209.0        Poor  2015      1   3        0.5   0.866025  0.433884   
3  ...  209.0        Poor  2015      1   4        0.5   0.866025 -0.433884   
4  ...  209.0        Poor  2015      1   5        0.5   0.866025 -0.974928   

    day_cos  AQI_Bucket_encoded  
0  0.623490                   2  
1 -0.222521                   2  
2 -0.900969                   2  
3 -0.900969                   2  
4 -0.222521                   2  

[5 rows x 23 columns]

In [55]:
pollutants = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene']
labels = ['City','year','month_sin','month_cos', 'day_sin', 'day_cos', 'AQI'] + pollutants

#AQI bucket model feature and target
X = cpollution_df[labels]
target_AQIB= cpollution_df['AQI_Bucket_encoded']

#AQI model feature and target
X_= cpollution_df[labels].drop('AQI', axis=1)
target_AQI= cpollution_df['AQI']

In [56]:
# Train-test split for AQI bucket
X_train, X_test, y_train, y_test = train_test_split( X, target_AQIB, test_size=0.2, random_state=42)

# Train-test split for AQI
Xb_train, Xb_test, yb_train, yb_test = train_test_split( X_, target_AQI, test_size=0.2, random_state=42)

In [57]:
preprocessor = ColumnTransformer(transformers=[('city', OneHotEncoder(handle_unknown='ignore'), ['City']),
        ('others', 'passthrough', ['year','month_sin','month_cos', 'day_sin', 'day_cos','AQI'] + pollutants)])

#classification pipeline to predict AQI_Bucket
AQIB_pipeline = Pipeline([('preprocessor', preprocessor),
    ('rf', RandomForestClassifier(n_estimators=200, random_state=42))])

AQIB_pipeline.fit(X_train, y_train)
y_pred = AQIB_pipeline.predict(X_test)
print('Classification accuracy:', accuracy_score(y_test, y_pred))
print('Classification report:\n', classification_report(y_test, y_pred))
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))

Classification accuracy: 0.9964448958862366
Classification report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       296
           1       1.00      1.00      1.00      2062
           2       0.99      0.99      0.99       666
           3       1.00      1.00      1.00      2033
           4       0.99      0.97      0.98       302
           5       0.98      0.99      0.99       548

    accuracy                           1.00      5907
   macro avg       0.99      0.99      0.99      5907
weighted avg       1.00      1.00      1.00      5907

Confusion matrix:
 [[ 293    0    0    3    0    0]
 [   0 2062    0    0    0    0]
 [   0    2  662    0    0    2]
 [   0    0    0 2033    0    0]
 [   0    1    1    0  293    7]
 [   0    0    3    0    2  543]]


In [49]:
preprocessor1 = ColumnTransformer([
    ('city', OneHotEncoder(handle_unknown='ignore'), ['City']),
    ('others', 'passthrough', ['year','month_sin','month_cos','day_sin','day_cos'] + pollutants)])

AQI_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor1),
    ("regressor", RandomForestRegressor(
        n_estimators=200,
        max_depth=5,
        min_samples_split=2,
        random_state=42,
        n_jobs=-1 ))])

AQI_pipeline.fit(Xb_train, yb_train)

yb_pred = AQI_pipeline.predict(Xb_test)

mae  = mean_absolute_error(yb_test, yb_pred)
mse  = mean_squared_error(yb_test, yb_pred)
rmse = np.sqrt(mse)
r2   = r2_score(yb_test, yb_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)





MAE : 30.649201214329366
MSE : 2856.067731427271
RMSE: 53.44219055603233
R²  : 0.8396200837874753


In [58]:
os.makedirs('models', exist_ok=True)
joblib.dump(AQIB_pipeline, 'models/aqib_classifier.pkl')
joblib.dump(AQI_pipeline, 'models/aqi_regressor.pkl')
joblib.dump(bucket_encoder, 'models/bucket_encoder.pkl')
print('Models saved in models/ folder')

Models saved in models/ folder
